language: python
dist: xenial
sudo: required
services:
- docker
cache: pip

install:
- virtualenv --version
- git config --global user.email "man-releaseengineering@manheim.com"
- git config --global user.name "Manheim RE"
- pip install tox
- pip install codecov
- pip freeze
- virtualenv --version

stages:
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: deploy
      python: '3.7'
      script: bash build_or_deploy.sh dockerbuild
      after_success: echo after_success
      deploy:
        provider: script
        script: bash build_or_deploy.sh dockerpush
        skip_cleanup: true
        on:
          tags: true

notifications:
  email:
    on_failure: always

branches:
  except:
  - "/^noci-.*$/"